flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "{{icon_asset_path}}"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "{{icon_asset_path}}"
    background_color: "{{background_color}}"
    theme_color: "{{theme_color}}"
  windows:
    generate: true
    image_path: "{{icon_asset_path}}"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "{{icon_asset_path}}"